title: Story Flow Typing Application
description: Documentation for the Story Flow Typing Application 
remote_theme: just-the-docs/just-the-docs

baseurl: "/story-flow-typing" # the subpath of your site
url: "https://randallard.github.io" # the base hostname & protocol

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Color scheme
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/randallard/story-flow-typing"

# Footer content
footer_content: "Copyright &copy; 2025 Your Name. Distributed under an MIT license."

# Configure search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Enable site back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy button
enable_copy_code_button: true

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green